# Generated by Django 5.0.6 on 2024-09-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_pdf', models.FileField(blank=True, null=True, upload_to='Project Report Sample/')),
                ('sample_ppt', models.FileField(blank=True, null=True, upload_to='Project Report Sample/')),
                ('format', models.FileField(blank=True, null=True, upload_to='Project Report Sample/')),
                ('school', models.CharField(choices=[('Sparsh Global School,Greater Noida', 'Sparsh Global SChool,Greater Noida'), ('JP International School, Greater Noida', 'JP International School, Greater Noida'), ('SPS,Sonipat', 'SPS,Sonipat'), ('Vivekanand School,Delhi', 'Vivekanand School,Delhi'), ('Blooming Dale School,Budaun', 'Blooming Dale School,Budaun'), ('Satya Prakash Public School, Jabalpur', 'Satya Prakash Public School, Jabalpur')], max_length=100)),
            ],
        ),
    ]
