# Generated by Django 5.0.6 on 2024-06-27 15:20

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20240618_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(max_length=100, validators=[users.models.validate_mobile_number]),
        ),
    ]
