# Generated by Django 5.0.6 on 2024-06-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_enquiry_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginactivity',
            name='user_agent_info',
            field=models.CharField(max_length=500),
        ),
    ]
