# Generated by Django 5.0.6 on 2024-07-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_observationsheet_alter_advocacyvisit_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('Sparsh Global School,Greater Noida', 'Sparsh Global SChool,Greater Noida'), ('JP International School, Greater Noida', 'JP International School, Greater Noida'), ('SPS,Sonipat', 'SPS,Sonipat'), ('Vivekanand School,Delhi', 'Vivekanand School,Delhi'), ('Blooming Dale School,Budaun', 'Blooming Dale School,Budaun'), ('Satya Prakash Public School, Jabalpur', 'Satya Prakash Public School, Jabalpur')], max_length=100)),
                ('curriculum_sheet', models.URLField()),
            ],
        ),
    ]
