# Generated by Django 5.0.6 on 2024-07-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_rename_page_useractivity1_page_visited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity1',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
