# Generated by Django 5.0.6 on 2024-07-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_alter_useractivity1_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='student',
        ),
        migrations.AddField(
            model_name='competition',
            name='student',
            field=models.ManyToManyField(related_name='competitions', to='users.user_profile_student'),
        ),
    ]
