# Generated by Django 5.0.6 on 2024-07-10 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_remove_competition_student_competition_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='student',
        ),
        migrations.AddField(
            model_name='competition',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_profile_student'),
        ),
    ]
