# Generated by Django 5.0.6 on 2024-07-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_remove_competition_student_competition_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationclub',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
