# Generated by Django 5.0.6 on 2024-07-11 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_innovationclub_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovationclub',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user_profile_student'),
        ),
    ]
