# Generated by Django 5.0.6 on 2024-07-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_alter_innovationclub_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='bill_of_materials',
            field=models.FileField(blank=True, null=True, upload_to='bills/'),
        ),
    ]
