# Generated by Django 5.0.6 on 2024-07-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_inventory_bill_of_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity1',
            name='curriculum_time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
