# Generated by Django 5.0.6 on 2024-07-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_useractivity1_curriculum_time_spent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocacyvisit',
            old_name='handling_comm_2',
            new_name='Punctuality',
        ),
        migrations.RenameField(
            model_name='advocacyvisit',
            old_name='regularity_punctuality',
            new_name='Regularity',
        ),
    ]
