# Generated by Django 5.0.6 on 2024-09-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_quiz_date_quiz_schools'),
        ('curriculum', '0007_userlessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='date',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='schools',
            field=models.ManyToManyField(to='curriculum.school'),
        ),
    ]
