# Generated by Django 5.0.6 on 2024-07-31 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(default='', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('author', models.CharField(max_length=100)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.standard')),
            ],
        ),
        migrations.CreateModel(
            name='Topic_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.CharField(max_length=50)),
                ('lesson_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('file', models.URLField(default='', max_length=300, verbose_name='content')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebook_lessons', to='ebook.ebook')),
            ],
        ),
    ]
