# Generated by Django 5.0.6 on 2024-08-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='schools',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='lessons', to='users.user_profile_school', verbose_name='Schools'),
        ),
    ]
