# Generated by Django 5.0.6 on 2024-08-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_school_lesson_schools_subject_schools'),
        ('curriculum', '0004_school_subject_schools_alter_lesson_schools'),
    ]

    operations = [
    ]
