# Generated by Django 5.0.6 on 2024-08-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_merge_20240822_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='schools',
            field=models.ManyToManyField(to='curriculum.school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='schools',
            field=models.ManyToManyField(to='curriculum.school'),
        ),
    ]
