# Generated by Django 5.0.6 on 2024-09-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_userlessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherlesson',
            name='module',
            field=models.CharField(blank=True, choices=[('Module 1', 'Module 1'), ('Module 2', 'Module 2'), ('Module 3', 'Module 3')], max_length=10, null=True, verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='level',
            field=models.CharField(blank=True, choices=[('Phase-I', 'Phase I'), ('Phase-II', 'Phase II'), ('Phase-III', 'Phase III')], max_length=10, null=True, verbose_name='Level'),
        ),
    ]
